baseURL = 'https://raymoniot.github.io'
languageCode = 'zh'
title = 'Solarhub 帮助中心'
contentDir = "content/zh/docs/web"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
publishDir = "docs"
[languages]
[languages.zh]
languageName ="中文"
title = "Soalrhub 帮助中心"
weight = 1
contentDir = "content/zh"
[languages.en]
languageName ="English"
title = "Solarhub Help Center"
weight = 2
contentDir = "content/en"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  [params.footer]
    copyright = "Copyright © 2024 RaymonIoT. All Rights Reserved."
  [params.search.algolia]
    appId = "UTU98CAGT1"
    apiKey = "4d3e8e1102314e0a038a07622c8165ac"
    indexName = "raymoniotio"
  [params.docs]
    logoLinkURL = "www.baidu.com"
    repoURL = "https://raymoniot.github.io"
    repoBranch = "main"
